# Generated by Django 5.1.4 on 2025-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_deposit_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference_number',
            field=models.CharField(default='fvGS5maob2mYHJ1wEC3W', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference_number',
            field=models.CharField(default='0qnReqiFU1wAHg30iRkd', max_length=50),
        ),
    ]
