<<<<<<< HEAD
# Generated by Django 5.1.4 on 2026-03-22 01:55
=======
# Generated by Django 5.1.4 on 2025-01-28 11:40
>>>>>>> 8fd357047b463a75560c6f6c577a5981f80b24cf

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('referral_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('reward_per_referral', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('referral_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.IntegerField(default=0)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('total_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('required_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
=======
                ('has_received_referral_reward', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('referrals', models.ManyToManyField(related_name='referred_users', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to=settings.AUTH_USER_MODEL)),
>>>>>>> 8fd357047b463a75560c6f6c577a5981f80b24cf
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the banner', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description for the banner', null=True)),
                ('image', models.ImageField(help_text='Upload a banner image', upload_to='banners/')),
                ('link', models.URLField(blank=True, help_text='Optional link for the banner', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
