# Generated by Django 5.1.4 on 2026-03-22 01:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('option', models.CharField(blank=True, choices=[('UP', 'UP'), ('DOWN', 'DOWN')], max_length=50, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('UP', 'UP'), ('DOWN', 'DOWN')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('Loss', 'Loss'), ('Won', 'Won')], default='PENDING', max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeadorTail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('option', models.CharField(blank=True, choices=[('Head', 'Head'), ('Tail', 'Tail')], max_length=50, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('Head', 'Head'), ('Tail', 'Tail')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('Loss', 'Loss'), ('Won', 'Won')], default='PENDING', max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Minislot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result1', models.CharField(max_length=20)),
                ('result2', models.CharField(max_length=20)),
                ('result3', models.CharField(max_length=20)),
                ('stake', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Won', 'Won'), ('Loss', 'Loss')], default='PENDING', max_length=30)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RockPapperSissors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('option', models.CharField(blank=True, choices=[('ROCK', 'ROCK'), ('PAPER', 'PAPER'), ('SISSORS', 'SISSORS')], max_length=50, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('ROCK', 'ROCK'), ('PAPER', 'PAPER'), ('SISSORS', 'SISSORS')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('Loss', 'Loss'), ('Won', 'Won'), ('Draw', 'Draw')], default='PENDING', max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
