# Generated by Django 5.1.4 on 2025-02-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headortail',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
